
receivers:
  otlp:
    protocols:
      grpc:
      http:
  opencensus:

  # Collect own metrics
  prometheus:
      config:
        scrape_configs:
          - job_name: 'prometheus-sample-app'
            scrape_interval: 10s
            static_configs:
              - targets: [ '0.0.0.0:8080' ]

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging]
