version: "2"
services:

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317"        # OTLP gRPC receiver

  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
    depends_on:
      - otel-collector

  # Synthetic load generator
  metrics-load-generator:
    build:
      dockerfile: $PWD/prometheus-sample-app/Dockerfile
      context: ./prometheus-sample-app 
    environment:
      - OTEL_AGENT_ENDPOINT=otel-agent:4317
    depends_on:
      - otel-agent

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
